### ISSUE TITLE
Delete old plugin files on fisher update

### ISSUE THREAD

**Issue by franciscolourenco** [jorgebucaran/fisher#361]
If a plugin releases a new version with deleted or renamed files, `fisher update` may result in duplicate files and unexpected functionality from plugins.

Would perhaps be a good idea to clean a plugin's previous files before linking new ones.

**Comment by jbucaran** [comment]
From conversation https://github.com/fisherman/done/issues/12#issuecomment-278049153.

**Comment by aristidesfl** [comment]
Would this be as simple as doing `fisher uninstall` automatically before performing `fisher install`?

**Comment by jbucaran** [comment]
@aristidesfl 🤔 Maybe, but that'd be unacceptably slow.

**Comment by aristidesfl** [comment]
Because of the plugins which don't need to be updated?

**Comment by jbucaran** [comment]
No, that's okay, you can always specify the name of the plugin/s you want to update.

Because removing the files will take some time, that's why. Probably, not too slow.

**Comment by jorgebucaran** [comment]
@franciscolourenco Fixed in [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0)~!  🎉:tada:

It works similarly as you originally suggested. Before installing any package, we'll remove it. This should remove old files (including files that no longer exist in a new version of the package).
