### ISSUE TITLE
Can't install local repos with `github.com` in the path

### ISSUE THREAD

**Issue by externl** [jorgebucaran/fisher#472]
eg.

```
❯ fisher add ~/src/github.com/externl/fish-symnav/
cannot install "~/src/externl/fish-symnav" -- is this a valid file?
...
```

**Comment by jorgebucaran** [comment]
@externl Good catch, thanks! Need to improve the fishfile parser.

**Comment by externl** [comment]
I'm not sure if there's some cache, because I"m not seeing this error for any `add`

**Comment by jorgebucaran** [comment]
I think the problem is here:

https://github.com/jorgebucaran/fisher/blob/1d82bee9c2341258161ebd27c3a936038c64678c/fisher.fish#L351-L356

We want `normalize` to remove `github.com` from every package URL only when it's at the begining of a string which can also be preceded by an arbitrary amount of whitespace.

```diff
- gsub(/^[ \t]*|[ \t]*$|https?:\/\/|github\.com\/|\.git$|\/$/, "", s) 
+ gsub(/^[ \t]*|[ \t]*$|https?:\/\/|^[ \t]*github\.com\/|\.git$|\/$/, "", s) 
```

Do you think you could change your fisher.fish file directly as shown in the diff above and try again?

**Comment by externl** [comment]
> Do you think you could change your fisher.fish file directly as shown in the diff above and try again?
That works!
