### ISSUE TITLE
Installing Gists and GitLab/BitBucket Snippets

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#505]
Fisher used to support installing packages from gists, but it was slow and I removed it from the 3.x release. 

We could give it another shot, this time with a limited scope, e.g. no prompts or configuration snippets, no version locking, and only single file functions. Also useful would be the ability to create gist aliases, so we don't have to remember what gist hash corresponds to what package.

```properties
fisher add triton=jorgebucaran/1afe48a489bfa20c2ec14fae41e7ec1f
```
```
fisher rm triton
```

**Comment by rhajdacki** [comment]
Would it be also possible to install single function/completion files from anywhere inside Git repo.
Like for example these Skim keybindings?
https://github.com/lotabout/skim/blob/master/shell/key-bindings.fish

**Comment by jorgebucaran** [comment]
@rhajdacki I looked into installing a file from a repository before (not a single function or completion). 

It was too tricky. It would be easier to create a package with that ability. I could write something over the weekend and share it here just for fun.

How often do I stumble upon fish code like a single file with function definitions, completions, and key bindings, and I want to add some of it to my scripts? Not as often as I encounter a proper package that follows a file structure I can already install with Fisher. If I really wanted that code, I'd ask the author to turn it into a package (or do it myself if there was no response).

> Like for example these Skim keybindings?

Even if we could install single files, those key bindings are not in the form of a [configuration snippet](https://github.com/jorgebucaran/fisher#configuration-snippets), so we wouldn't be able to manage them correctly (no proper updating or removing within the same session).

I suggest you turn some of that code into a package and manage it as you would any other fish package with Fisher. Let me know if you need help with that.

**Comment by reitzig** [comment]
@jorgebucaran How do you feel about custom tarballs (instead of the full-repo ones)?

Background: What if you generate fish completion scripts programmatically? Ideally, you'd want to source-control the script, have build automation run it, and deliver the result. 

One way well-defined approach using GitHub would be through release assets. You could 

 - define which canonical path or name it would have to have,
 - require the user to specify the asset name together with a version ,e.g. `:owner/:repo/:asset@:release`, or
 - pull [information about the latest version](https://developer.github.com/v3/repos/releases/#get-the-latest-release)  `assets`.

Using the latest release instead of the latest commit by default would have other advantages (including independence of source repo structure and size, can check timestamps to determine whether updates have to happen at all, ...), but that's probably for another discussion.

**Comment by jorgebucaran** [comment]
Hi @reitzig. I don't know what that has to do with this issue?

**Comment by jorgebucaran** [comment]
Closing here as well, as I'm not going to implement this.
