### ISSUE TITLE
git-open fisher support

### ISSUE THREAD

**Issue by MartinDelille** [jorgebucaran/fisher#519]
Hi! I would like to add [fisher](https://github.com/jorgebucaran/fisher) support for the *git-open* plugin (https://github.com/paulirish/git-open/issues/136). It seems that I just need to add the git-open folder to the PATH.

It looks like that I need to write a `conf.d/git-open.fish` script doing that but I've no idea how to achieve this. Any idea?

**Comment by jorgebucaran** [comment]
@MartinDelille I don't recommend using Fisher for this. Let me tell you why.

[`git-open`](https://github.com/paulirish/git-open/blob/4eed00f282aa7bcb9e7b27f8ad257efa2a064448/git-open) is an executable script. All you need is add its location to the `$PATH`. If you are on macOS you can drop it on `usr/local/bin`. 

But what if you don't want to go mucking around in directories? Then you need a systems package manager. Every OS has something like that. If you are on macOS, `brew` or `npm` are your friends. If you are on Linux, you probably know already.

Fisher is a package manager for the fish shell, i.e., for `.fish` scripts. It doesn't alter your `$PATH` or your environment. Its job is to put `.fish` files in the right place so that fish can find them.

Hardcoding `$fisher_path` and `git-open` in `conf.d/git-open.fish` in the root of the project will work, but please don't do it. 

```sh
set -gx PATH ~/.config/fisher/github.com/paulirish/git-open $PATH
```

So, what are your options? Writing your own pure-fish, `fish-git-open` package comes to mind.

Just let me know if you need help with that! 👋

**Comment by MartinDelille** [comment]
I didn't know about the `brew` package and your right it is the best option. Thank you for your time and your awesome package manager!

**Comment by jorgebucaran** [comment]
Thank you for your interest and your inquiry! 💯
