### ISSUE TITLE
Rename fishfile to fish_plugins

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#524]
Merely for aesthetic consistency. There is already a `fish_history` and `fish_variables` file in your `~/.config/fish` directory. Renaming `fishfile` to ~~`fish_bundle`~~ (or ~~`fish_file`~~) **`fish_plugins`** would be nice. 

```console
$ la ~/.config/fish
jb  staff   320B Jan 31 00:51 .
jb  staff   448B Jan 31 00:48 ..
jb  staff   128B Jan 31 00:48 completions
jb  staff   128B Jan 31 00:48 conf.d
jb  staff   190K Jan 28 18:31 fish_history
jb  staff   1.3K Jan 31 00:51 fish_variables
jb  staff    22B Jan 31 00:48 fish_bundle
jb  staff   256B Jan 31 00:48 functions
```

**Comment by ammgws** [comment]
What about `fisher_bundle`? At least to make it obvious where the file comes from.

**Comment by patrickf3139** [comment]
Besides aesthetic consistency, I also like either `fish_bundle` or `fisher_bundle` because fishfile could refer to so many different things. I mean, the name only implies a file having to do with fish.

**Comment by mattmc3** [comment]
I'm willing to submit a PR for this if we can agree on the naming @jorgebucaran. I'm partial to fish_bundle rather than fisher_bundle since it's really just a list of fish plugins and not anything with fisher specific data or formatting, so it could even be used by other fish plugin management tools, but honestly, whatever you want is fine.

My questions are: Is this still something we want to do, and are there any other requirements other than simply:

1. Change the name of fishfile to fish_bundle
2. Handle migration of fishfile to fish_bundle if the former exists, but not the latter

**Comment by jorgebucaran** [comment]
@mattmc3 I like `fish_bundle` too. It just looks cool. I get that `fisher_bundle` would be a safer approach, but then we might as well leave things the way they are.

I'm happy to go with this if we can agree on `fish_bundle`.

/cc @franciscolourenco @edouard-lopez @FabioAntunes @Scrumplex @neersighted 

> ...are there any other requirements other than simply:

1 and 2 sound good. We also need to update the docs. And we need to continue to support `fishfile` for the time being. After this, I suggest we establish a small "school of fish" friends and send PRs to people still using `fishfile` to rename it to `fish_bundle` as we encounter them in the wild, e.g., [here](https://github.com/franciscolourenco/done/blob/9351f5a9f4ae6c73dd6f18e41364e63a77be5d90/fishfile).

**Comment by franciscolourenco** [comment]
The word bundle could be hard to understand for people who are not part of certain circles. Would `fish_packages` correctly describe what the file contains?

**Comment by neersighted** [comment]
`fish_bundle` is fine by me but I don't really have a strong opinion either way.

**Comment by mattmc3** [comment]
The word "bundle" has quite a bit of history in other CLI projects for a collection of 3rd party code. Homebrew uses bundle. Vim's Vundle is a play on the word bundle. Ruby has bundler. ZSH's antigen uses the term bundles too. The list is not short. 

While it's a valid point that there are other common descriptive words like "package" or "module" or "libraries" in this context, I think that it can be a bit of an advantage to use a less overused synonym like "bundle". It stands out without being obscure or losing its meaning, and conveys the grouping-together functionality that fisher provides.

**Comment by franciscolourenco** [comment]
I won't argue against bundle, because I'm not familiar this historical convention and it it might have value. However it might be unclear for other people like me, and a convention that is not clear it might not be worth propagating. Anyway there are a couple of points I should mention:

1. The suggestion was for the plural form - "packages", not package.
2. Does fish it actually group packages together somehow, like webpack for example? Or is it rather just installing them? Perhaps this is where my confusion comes from.
3. Homebrew has a bundle command, but users a brewfile for the dependency list. Ruby bundler also has a gemfile. In this case we would be using a term which might still be ambiguous, while at the same time actually breaking convention.

I'm not a native english speaker and I'm more influenced by the Javascript tooling system than the Ruby one, so that could my source of confusion.

**Comment by jorgebucaran** [comment]
Hmm, `fish_packages` is not bad at all, but there's something about `fish_bundle` that just clicks for a shell project!

@mattmc3 Would you like to send me that PR? Let's go with `fish_bundle`, but we can keep collecting feedback in the meantime. I hope everyone's cool with this.

**Comment by vyasknellutla** [comment]
While Bundle is a common term used for the program & CLI commands managing packages, projects that have similar tools to bundler usually have the naming convention "<PackageType>file":
- [Bundler](https://github.com/rubygems/rubygems/tree/master/bundler) uses "Gemfile" for ruby gem packages
- [Homebrew-bundle](https://github.com/Homebrew/homebrew-bundle#homebrew-bundle) uses "Brewfile" for homebrew (brew, tap, cask, mas, & whalebrew) packages
- [Pipenv](https://github.com/pypa/pipenv#pipenv-python-development-workflow-for-humans) uses "Pipfile" for python pip packages

I would prefer one of the following options:
- "Fishfile" - matches convention set by other projects, but breaks the fish naming convention
- "fish_file" - matches fish naming convention, while staying close enough to the standard to be recognizable

**Comment by jorgebucaran** [comment]
I'm going with fish_bundle for fisher 4.0. I hope we're all cool with this.

**Comment by franciscolourenco** [comment]
What was the arguments for `fish_bundle` instead  of `fish_file`? It seems like the later is a more common name.

**Comment by jorgebucaran** [comment]
> The word bundle could be hard to understand for people who are not part of certain circles. Would fish_packages correctly describe what the file contains?

I admit that I like `fish_bundle`. That was my original plan as that is the title of this issue, but in re-reading your question I realized that `fish_bundle` could never correctly and instantly describe what the file contains, whereas `fish_plugins` would, wherever your background is.

So, I now feel strongly in favor of `fish_plugins` and have a good reason as well.

**Comment by mattmc3** [comment]
As I was considering helping with the PR, this discussion leads me to agree that this kind of breaking change makes way more sense to wait for the 4.0 release.

**Comment by jorgebucaran** [comment]
@mattmc3 Absolutely. I've updated the milestone to reflect this as well. The good news is that 4.0 lands very soon! 💯

**Comment by jorgebucaran** [comment]
Implemented in [4.x](https://github.com/jorgebucaran/fisher/releases/tag/4.0.0).
