### ISSUE TITLE
custom fish_greeting overwrite after fisher update all package

### ISSUE THREAD

**Issue by kenchou** [jorgebucaran/fisher#539]
* install plugin
  * laughedelic/fish_logo
  * oh-my-fish/theme-bobthefish

* add fish_logo to ~/.config/fish/functions/fish_greeting.fish
```
function fish_greeting
    type -q fish_logo; and fish_logo
end
```
* and start new session will see the fish logo
* after execute `fisher`, the `~/.config/fish/functions/fish_greeting.fish` has been changed (provide by theme-bobthefish), and my greeting was lost.
```
function fish_greeting -d "What's up, fish?"
    set_color $fish_color_autosuggestion
    uname -nmsr

    # TODO: `command -q -s` only works on fish 2.5+, so hold off on that for now
    command -s uptime >/dev/null
    and uptime

    set_color normal
end
```

**Comment by jorgebucaran** [comment]
@kenchou That's what I expect to happen when I install `bobthefish` since `fish_greeting.fish` is part of that package.

If you want to install `bobthefish` but preserve your previous `fish_greeting.fish`, you could customize Fisher's installation prefix to a different location using the `$fisher_path` env variable as described in the docs.

**Comment by Odaeus** [comment]
I just came here to open a very similar issue. I installed Spacefish via Fisher and it overwrote my `fish_prompt` files 😞. It was totally unexpected as no package manager I'm familiar with would behave in that way. For example, `apt` will ask whether files should be overwritten or Vim's Pathogen has each package in its own directory.

@jorgebucaran Can I please ask you to really add a specific warning to the README stating that Fisher will overwrite files if they are contained in a package? I know there is wording under "Changing the installation prefix" similar to this but it reads like the focus is simply on personal directory organisation rather than such an important caveat.

**Comment by jorgebucaran** [comment]
@Odaeus Why did you think was going to happen to your `~/.config/fish/fish_prompt.fish` after you installed Spacefish?

**Comment by Odaeus** [comment]
@jorgebucaran I didn't think about the internal workings of Fish or Fisher at all. Obviously I expected my prompt config to be superseded in some way, but my surprise was that it destroyed the original data. If these were files that users aren't supposed to touch, then sure, but my understanding is that these are user-controlled files. I suppose I expected perhaps a prompt asking "overwrite this file?" before it proceeded, or that Fisher packages were kept separate and used path wrangling to override user-defined functions.

**Comment by Odaeus** [comment]
> Not an actual code solution, but a note in the README as you suggest works for me. PR welcome! :)

Sure will do that, thanks!

**Comment by jorgebucaran** [comment]
> @Odaeus ...a prompt asking "overwrite this file?" before it proceeded, or that Fisher packages were kept separate and used path wrangling to override user-defined functions.

Ah, yes, that's another option. Fisher used to be a lot more interactive in the past, but I've since gone in the opposite direction, favoring a more brutal (minimal) approach. I'd find a prompt extremely annoying. I didn't want logs or have even a CLI, but I couldn't get people on board with that #443 #445.  

> Sure will do that, thanks!

Thank you! 💯
