### ISSUE TITLE
Plugin uninstall hook

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#543]
Hi Jorge, I am currently developing some fisher plugins and want to be able to clean up whatever my plugins install. I read the section about the uninstall event that gets emitted on uninstall in https://github.com/jorgebucaran/fisher#configuration-snippets. Looking for a concrete example, I read Jethro Kuan's z code. I was surprised to see that he didn't use that hook but simply created an `uninstall.fish` in `functions/`. See https://github.com/jethrokuan/z/blob/master/functions/uninstall.fish. It seems this is undocumented. Could you explain a bit about how fisher uses `uninstall.fish` and the differences between it and the uninstall event emitted for cleaning up plugins?

**Comment by jorgebucaran** [comment]
Hi @patrickf3139, support for `uninstall.fish` may disappear at any time, and without prior notice. Please use a `conf.d` snippet with a function that registers a `file_name_uninstall` event.

For example, `conf.d/foobar.fish`:

```fish
function foobar_uninstall --event foobar_uninstall
    echo "Uninstalling foobar..."
end
```

**Comment by patrickf3139** [comment]
Thanks for the reply Jorge! It seems to me the `uninstall.fish` hook is much more elegant and lower overhead, no? (lower overhead because you don't need to create a function and add a event handler)

Thank you for creating and designing fisher.

**Comment by jorgebucaran** [comment]
@patrickf3139 There is no such thing as "hooks" in fish. Conf.d is the shell's canonical autoload mechanism; therefore, it makes sense to re-use it, rather than fabricating a custom file convention. We also use conf.d to un/register key bindings. If your package is a configuration snippet, you already have a file (or files) that load during startup too. This place is where your init, uninstall, and (in the future, someday https://github.com/jorgebucaran/fisher/issues/527) update logic belongs.

> It seems to me the `uninstall.fish` hook is much easier to use and more efficient, no?

Easier? I don't think so. This assertion is opinion-based, so you're welcome to disagree. More efficient? No, it's less efficient. You're going to check for file existence when you try to run it (even if it doesn't exist). And you may already be using a configuration snippet anyway.
