### ISSUE TITLE
RFC: Fisher 4.0 

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#582]
Let's talk about Fisher 4.0. What would you like to see? What would you like to go away?

## `_install`, `_update` and `_uninstall` event system

We have `_uninstall` events, but not `_install` or `_update`. Starting with 4.0 plugin authors should be able to reliably know when their plugin is installed, updated, or uninstalled. Related #526 #527 #573.

## ~~Oh My Fish~~

I'd like to remove some OMF plugin support (it won't go away completely since more than less of OMF plugins actually work fine). But this means to fully deprecating `init.fish`, `uninstall.fish`, etc. See #581. The irony is that [I introduced these conventions back in the day](https://github.com/oh-my-fish/oh-my-fish/commit/2693a2fd18bd92a439f4d74b10513922d92120f7#diff-0545f24fb8f326335e8151d51cbb5c2d) to OMF. So long, and thanks for all the fish!

## Less is more

I don't consider Fisher a [big ball of mud](https://en.wikipedia.org/wiki/Big_ball_of_mud) (yet), but could it be simpler? Yes. Less features = less complexity && less bugs && more maintainability. I still consider some features essential such as concurrent downloads, but I'm curious to see what else could go away, e.g., plugin dependencies, private package hosts (#464), gitlab/bitbucket support. See also: #579.

## Other

- Require fish 3.0, use newer fish features, e.g., use `wait` to implement concurrent downloads.
- Rely less on external tools. No awk, no sed, no basename/dirname. Just mv, rm, cp, and mkdir.
- Remove support for private package hosts. 
- Deprecate `fishfile` in favor of ~~`fish_bundle`~~ → `fish_plugins`. See #524.
- Needless to say, but upgrading to fisher 4.0 should be smooth and painless. 

## Timeline

~~I'll probably have enough time to begin working on this sometime in 2021.~~ 

~~I've been working on this for a while now and I might be able to finish it sooner, before December.~~

Fisher 4.0.0 lands this week. 🎉

**Comment by IlanCosman** [comment]
Less awk if that's a possibility. The average fish user/scripter like myself isn't likely to know awk syntax etc. which makes it mucrh harder to understand the code and possibly contribute. I know next to nothing about fisher's code, but are there really places where pure fish is insufficient? I think fisher 4.0 should do it's best to use no or very little awk.

**Comment by jorgebucaran** [comment]
@IlanCosman It's worse without awk for some of the most complex things like parsing the fishfile as the equivalent with fish built-ins could possible 10-fold the amount of code, but part of the idea of upgrading to fish 3.0 is using more of the fish built-ins for simple cases, validating a path, etc. 👍

**Comment by IlanCosman** [comment]
I really don't feel strongly about this at all, but my brothers, both CS majors, have always cautioned me against brevity over clarity. Personally I would rather use 30 lines of step-by-step fish rather than 5 lines of dense awk, but I understand you may feel differently.

Then again my first programming language was Java so.... 😂

**Comment by jorgebucaran** [comment]
@IlanCosman Give it 5 minutes. The syntax is not all that different from Java. It's so easy it hurts. And if you already know JavaScript, then you already know AWK's grammar. 

Fish built-ins and may change in the future as well, new built-ins or built-in flags can be added, etc. AWK will just keep working. It's churn. Anyway, AWK or not is beside the point. I should be able to use less of it in Ⅳ for sure. 😂

**Comment by jorgebucaran** [comment]
@IlanCosman Give it 5 minutes. The syntax is not all that different from Java. It's so easy it hurts. And if you already know JavaScript, then you already know AWK's grammar. 

Fish built-ins may change in the future as well, new built-ins or built-in flags may be added, etc. AWK will just keep on working. It's less churn. Anyway, AWK or not is beside the point. I should be able to use less of it in Ⅳ for sure. 😂

**Comment by patrickf3139** [comment]
> The irony is that I introduced these conventions back in the day when I still contributed to OMF.
Wow didn't know you were also a major OMF contributor. That's cool, and thank you for your contributions to that project as well!

> Less awk if that's a possibility.

I also agree that the parsing that happens should be done using awk. @IlanCosman awk is actually a dying but pretty commonly used tool in the software industry, so I as a software engineer also know how to read and write some awk. It's incorporated into major tools such as vim.

> What would you like to see?

- Not specific to the code but I'd like to see a tiny bit more documentation around creating packages. e.g. naming conventions, guiding principles, maybe one or two packages that you uphold as good examples.
- Would you mind reconsidering this? https://github.com/jorgebucaran/fisher/issues/550
- Output which packages are being removed or added on executing `fisher` (after manually editing the fishfile), `fisher rm` or `fisher add`
- A command to force refresh the cache. I've run into bugs where the cache was preventing new versions from being downloaded.

**Comment by vyasknellutla** [comment]
>     * Deprecate `fishfile` in favor of `fish_bundle`. See #524. Maybe this is a good opportunity to figure out a way to make parsing and formatting this file more easily too.

For parsing & formatting, would an existing configuration file format be up for consideration? Since the `fishfile` is currently a list of repositories, an existing format could allow you to leverage existing packages/commands to parse the configuration file.

Some considerations:
- [TOML](https://github.com/toml-lang/toml): My preference due to simplicity
- [YAML](https://github.com/yaml/yaml-spec)
- [JSON](https://www.json.org/json-en.html)
- [INI](https://en.wikipedia.org/wiki/INI_file): An option, but can be hard to maintain since it doesn't have a consistent spec.

**Comment by jorgebucaran** [comment]
@vyasknellutla Probably not.

**Comment by mattgreen** [comment]
Biggest thing I'd like to see in a breaking release is defaulting to installing packages somewhere other than `~/.config/fish`. I'd argue the behavior is surprising enough to warrant being changed even if it means a bit more code. Perhaps `~/.config/fisher` or `~/.config/fish/packages`?

> fish 3.0? This means we could use more fish builtins

Totally fair.

**Comment by IlanCosman** [comment]
I would strongly argue against that @mattgreen. Why is this behavior surprising to you? To me this is the only logical way of doing it. When _**I**_ create functions, I put them in the functions directory. When I "install" a fisher "package" it's just a bunch of fish functions that someone else made, and there's no reason they shouldn't go in the usual spot.

**Comment by mattgreen** [comment]
I advocate separating the user's custom fish config from package contents because a package can inadvertently clobber user-written functions/completions/config snippets of the same name. I've done this before, and I should've read the docs. (Thank goodness for git.) Moving them to another directory protects user-specific configuration. It doesn't fix the fact that packages can clobber each other's functions, but I see that as a much smaller problem.

Related: can't remember off-hand if this is true, but AFAIK all package repos are updated for every mutable invocation of `fisher` (e.g. adds/remove/update). This means that malicious `fisher` packages will propagate faster than they would if they were manually updated. This is a difficult problem to solve completely and may be out of scope, but IMO justifies code to handle add/remove/update separately, rather than starting from scratch each time. (Pinning versions could work too.)

**Comment by IlanCosman** [comment]
I see what you're saying about clobbering. Perhaps fisher should ask the user about any files that it would clobber?

**Comment by vyasknellutla** [comment]
Since fisher is installing plain-text fish code, I'm personally fine with it being in ~/.config/fish.

But if it is something we're considering, how about storing it in `$XDG_DATA_HOME/fisher` (by default: `~/.local/share/fisher`) alongside the rest of the data fisher stores?

I can see a case be made if people would like to check in `$XDG_CONFIG_HOME/fisher` (by default: `~/.config/fisher`) as a part of their dotfiles, but leave out files that fisher can generate from the configuration file `fishfile`.

**Comment by jorgebucaran** [comment]
> @mattgreen Biggest thing I'd like to see in a breaking release is defaulting to installing packages somewhere other than ~/.config/fish. I'd argue the behavior is surprising enough to warrant being changed even if it means a bit more code.
>
> [...] I advocate separating the user's custom fish config from package contents because a package can inadvertently clobber user-written functions/completions/config snippets of the same name.

I'm actually considering deprecating `$fisher_path`. What? This won't even allow changing the installation path. How am I going to separate my own user-written functions/completions/snippets with other stuff I install with Fisher?

Let's say I use a rod to fish and you use a net. Fisher is like a rod, but you're trying to use it like a net. I totally get that there are many ways to fish, but Fisher's way is the way I do it and advocate for with this tool. Here's how it works:

_Fisher_ will handle `~/.config/fish` for you. Period.

But what if I want to write my own function/completion/snippet and put them there? Every time I run `fisher` I risk overwriting files that have the same name brought over from a different plugin. *True*. That's why you're not going to put anything there! 

Huh? So where do I put my functions or whatever? That's totally up to you, e.g., `~/fish/plugins/utils`, it doesn't matter. Then install it: 

```console
fisher add ~/fish/plugins/utils
``` 

Now removing that is just as easy. And because local files are installed as symlinks, updating your stuff as simple as editing the original files. 

> Principle of Least Astonishment seems to be the fish ethos. 

This argument can stifle creativity too. 

> Moving them to another directory protects user-specific configuration. It doesn't fix the fact that packages can clobber each other's functions, but I see that as a much smaller problem.

It doesn't fix the fact that in fish all functions are in the same scope. Using fish (and the shell for that matter) is like being inside a REPL (forever), like when you're inside the Node REPL, etc. Matt: Maybe the biggest issue here is that you want to keep using fish the way you always have alongside with Fisher and expect them to be 100% compatible. They are largely compatible, but the ideal usage is actually how I described it above. If you can buy that, you'll get the best out of Fisher.

---

**Comment by jorgebucaran** [comment]
> About deprecating `$fisher_path`. 

So, `$fisher_path` lets you customize the installation path, but allowing you to work around Fisher's usage philosophy you only end up hating Fisher because it doesn't perfectly adjust to how you think of fish. If people are absolutely against Fisher's default behavior, then maybe Fisher is not for them? Anyway, this is just a thought. Notice I didn't even mention it [here](https://github.com/jorgebucaran/fisher/issues/582#issue-670483651).

**Comment by mattgreen** [comment]
@jorgebucaran, your approach is out of the box but has promise IMO. It is certainly a conceptual shift from the file-centric approach taken by users and utilities (e.g. `stow`). I suspect more of the work will be around educating users than the code itself.

Otherwise it is very clean and I'll give it a try. It might or might not click, but that's not on you.

**Comment by IlanCosman** [comment]
Any updates on this? I'm excited to use fisher and trim down my code base 😂

**Comment by jorgebucaran** [comment]
@IlanCosman Unfortunately, none at the moment, but I really can't wait to start working on this.

**Comment by andreiborisov** [comment]
What I would like from the new major Fisher release is the ability to reliably use non `.fish` files in packages. The case for the fish-only packages seems somewhat limited for me since it’s often useful to include at least some template or config files in the package.

Now, Fisher downloads and manages them just fine already. The problem is you can’t reliably access those files from fish scripts, since `.fish` files are symlinked/copied into `functions` directory while everything else is left behind under Fisher managed directories. You can determine where the original package is located, but it’s somewhat complicated. More importantly, since Fisher’s private directory structure is an implementation detail, it’s brittle.

So, question is, how it is possible to access non `.fish` files from a fisher package script?

I see 2 potential solutions.

Ideally, all the package files would be stored together in the `functions` directory, this  implies some folder-per-package structure there. Which perhaps can help with potential naming conflicts.

The other solution is to provide a command like `fisher package locate` which would print the package original location. There is a big downside with this approach, however: it would require the package to explicitly use that command, which hurts package portability greatly.

@jorgebucaran I would love to hear you thoughts on this particular issue🙏

**Comment by IlanCosman** [comment]
Relevant: https://github.com/jorgebucaran/fisher/issues/581

**Comment by jorgebucaran** [comment]
@andreiborisov As @IlanCosman mentioned, #581 would allow you to create e.g., a directory inside your plugin's `functions` directory. During the install, fisher would copy this directory to your `~/.config/fish/functions` (together with any `*.fish` functions therein as usual). You can now access this directory and whatever is inside `(status -f)/directory`, `$fisher_path/functions/directory`, or `$__fish_config_dir/functions/directory`.

**Comment by jorgebucaran** [comment]
Fisher [4.x](https://github.com/jorgebucaran/fisher/releases/tag/4.0.0) is now available. :tada:

If you are using in Fisher 3.x, you can upgrade to 4.x by running

```console
fisher self-update
```

For everything else, check out [the new documentation](https://github.com/jorgebucaran/fisher#fisher).
