### ISSUE TITLE
`fisher list` should show me both what I have now and what I'll have after `fisher update`

### ISSUE THREAD

**Issue by lilyball** [jorgebucaran/fisher#610]
Right now `fisher list` only shows me what I have installed right now. This doesn't tell me what I will have after running `fisher update`.

Ideally I think the output of `fisher list` would read both the `fish_plugins` file and whatever I have right now, combine (and unique) them, and then show the list with annotations telling me which entries will be removed after `fisher update` and which entries are not yet installed but will be installed after `fisher update`.

**Comment by jorgebucaran** [comment]
@lilyball Cool feature idea. Is there any prior art to this? And why should Fisher tell you what you'll have after running `fisher update`?

**Comment by jorgebucaran** [comment]
@lilyball Cool feature idea. Is there any prior art to this? It's not immediately clear to me the reason I'd want this, though. Why should we add this to Fisher?

**Comment by PatrickF1** [comment]
This is similar to https://github.com/jorgebucaran/fisher/issues/499.
Re: Prior art. Check out how Ruby's bundler does it. When it's updating to a new version for a dependency, it tells you the old version and what the new version is. And if there's no change it says something like "already installed".

**Comment by jorgebucaran** [comment]
This issue is more about showing you the state after `fisher update` without actually running `fisher update`, not improving Fisher's output as in @PatrickF1's issue (#499). Running `fisher update` now tells you what was installed and removed:

```console
$ fisher update
fisher update version 4.2.0
Removing /home/jb/getopts.fish
         /home/jb/.config/fish/functions/getopts.fish
Installing /home/jb/fisher
           /home/jb/.config/fish/functions/fisher.fish
           /home/jb/.config/fish/completions/fisher.fish
Installing /home/jb/autopair.fish
           /home/jb/.config/fish/functions/_autopair_backspace.fish
           /home/jb/.config/fish/functions/_autopair_insert_left.fish
           /home/jb/.config/fish/functions/_autopair_insert_right.fish
           /home/jb/.config/fish/functions/_autopair_insert_same.fish
           /home/jb/.config/fish/functions/_autopair_tab.fish
           /home/jb/.config/fish/conf.d/autopair.fish
Installing /home/jb/nvm.fish
           /home/jb/.config/fish/functions/_nvm_index_update.fish
           /home/jb/.config/fish/functions/_nvm_list.fish
           /home/jb/.config/fish/functions/_nvm_version_activate.fish
           /home/jb/.config/fish/functions/_nvm_version_deactivate.fish
           /home/jb/.config/fish/functions/nvm.fish
           /home/jb/.config/fish/conf.d/nvm.fish
           /home/jb/.config/fish/completions/nvm.fish
Installing /home/jb/fishtape
           /home/jb/.config/fish/functions/fishtape.fish
           /home/jb/.config/fish/completions/fishtape.fish
Installing /home/jb/replay.fish
           /home/jb/.config/fish/functions/bax.fish
           /home/jb/.config/fish/functions/replay.fish
           /home/jb/.config/fish/completions/replay.fish
Installing /home/jb/spark.fish
           /home/jb/.config/fish/functions/spark.fish
           /home/jb/.config/fish/completions/spark.fish
Installing /home/jb/hydro
           /home/jb/.config/fish/functions/fish_mode_prompt.fish
           /home/jb/.config/fish/functions/fish_prompt.fish
           /home/jb/.config/fish/functions/fish_title.fish
           /home/jb/.config/fish/conf.d/hydro.fish
Installing /home/jb/humantime.fish
           /home/jb/.config/fish/functions/humantime.fish
Installing /home/jb/gitio.fish
           /home/jb/.config/fish/functions/gitio.fish
           /home/jb/.config/fish/completions/gitio.fish
Installed 2, Updated 7, Removed 1 plugin/s
```

Yes, it displays **"Installing..."** for plugins that we're technically updating because there's no easy way to tell if the plugin was actually updated or just re-installed. We do know if the user intention is to install or update, so changing that to **"Updating..."** can be easily done, the question is: would that be useful? If the answer is yes, let's do it.


Back to this issue, we know that the state will be whatever you have in your `fish_plugins`, so to see the difference, you can compare  `fisher list` and `fish_plugins` using your favorite diffing tool. 

```fish
$ fisher list | diff \
    --new-line-format="\x1b[31m+ %L\x1b[39m" \
    --old-line-format="\x1b[32m- %L\x1b[39m" - $__fish_config_dir/fish_plugins | string unescape
```
```diff
/home/jb/fisher
- /home/jb/autopair.fish
- /home/jb/nvm.fish
- /home/jb/spark.fish
- /home/jb/hydro
- /home/jb/fishtape
- /home/jb/replay.fish
- /home/jb/humantime.fish
- /home/jb/gitio.fish
+ /home/jb/kraken
+ /home/jb/nemo
+ /home/jb/ponyo
```

If that doesn't work on your box (it worked on macOS), try `diff` without flags. I don't know any other diffing tools off the top of my head, but there must be a ton! You could also use `git diff --no-index`.

I don't want to add a special flag to `list` because you already have all the information you need to diff it. Fisher doesn't have much special knowledge that would allow us to improve what you can do with some command-line-fu. 

I'm not saying write a new tool to solve this. I'm saying that by using a combination of `fisher list`, and `fish_plugins`, and a diffing utility you can get the job done. We don't want to create a Rube Goldberg machine. 

Small is beautiful, make each program do one thing well, and use composition. Closing.

**Comment by PatrickF1** [comment]
> Small is beautiful, make each program do one thing well, and use composition.

Just wanted to say that's a beautiful statement that echos exactly how everything should be built.
