### ISSUE TITLE
Bring Back Documentation on Plugins

### ISSUE THREAD

**Issue by nickeb96** [jorgebucaran/fisher#618]
It looks like the documentation in the readme on how to create your own plugins was removed.  Specifically the content under "What is a plugin?" and "Creating your own plugin" was very helpful in the past, but is no longer there.

It might be helpful to return the content for people who want to know how create their own plugins.  It was last present in version 3.3.2, but it's likely that some of the information would need to be updated for fisher 4.

I also have a question about declaring dependencies.  Previously, plugins could have a `fishfile` at the root and fisher would install plugins listed in that file.  Should it be renamed to `fish_plugins` or is that behavior no longer supported?

**Comment by jorgebucaran** [comment]
@nickeb96 Sure thing, I'll bring it back.

> Should it be renamed to fish_plugins or is that behavior no longer supported?

No longer supported. My reasoning is, few plugins actually use dependencies. No plugins listed on https://git.io/awesome.fish use dependencies. Some do, but those are mine and I am currently rewriting them. In fish all your dependencies are global dependencies, so, if your plugin requires, let's say, `piyo/poyo`, just tell the user to install `piyo/poyo` too, preferably in your README#installation's section.

Related: https://github.com/jorgebucaran/fisher/issues/582 https://github.com/jorgebucaran/fisher/issues/609 https://github.com/jorgebucaran/fisher/issues/614

**Comment by jorgebucaran** [comment]
Sure thing, I'll bring it back.

> Should it be renamed to fish_plugins or is that behavior no longer supported?

I removed this feature because, frankly, few plugins actually ever used dependencies. No plugins listed on https://git.io/awesome.fish use them. Now, some do, but those are actually mine (and I am currently rewriting them). In fish all your dependencies are global dependencies, so, if your plugin requires, let's say, `piyo/poyo`, just tell the user to install `piyo/poyo` too, preferably in your README#installation's section.

Related: https://github.com/jorgebucaran/fisher/issues/582 https://github.com/jorgebucaran/fisher/issues/609 https://github.com/jorgebucaran/fisher/issues/614
