### ISSUE TITLE
Strange error on update

### ISSUE THREAD

**Issue by aureooms** [jorgebucaran/fisher#633]
I get the following (or similar) **No matches for wildcard ...** error at random (yes, at random) when updating:

```
fetching https://codeload.github.com/oh-my-fish/plugin-sudope/tar.gz/HEAD
fetching https://codeload.github.com/oh-my-fish/plugin-fasd/tar.gz/HEAD
fetching https://codeload.github.com/wfxr/forgit/tar.gz/HEAD
installing oh-my-fish/plugin-fasd
+/home/aureooms/.config/fish/functions/__fasd_print_completions.fish
+/home/aureooms/.config/fish/functions/a.fish
+/home/aureooms/.config/fish/functions/d.fish
+/home/aureooms/.config/fish/functions/f.fish
+/home/aureooms/.config/fish/functions/fasd_cd.fish
+/home/aureooms/.config/fish/functions/init.fish
+/home/aureooms/.config/fish/functions/s.fish
+/home/aureooms/.config/fish/functions/sd.fish
+/home/aureooms/.config/fish/functions/sf.fish
+/home/aureooms/.config/fish/functions/z.fish
+/home/aureooms/.config/fish/functions/zz.fish
+/home/aureooms/.config/fish/completions/a.fish
+/home/aureooms/.config/fish/completions/d.fish
+/home/aureooms/.config/fish/completions/f.fish
+/home/aureooms/.config/fish/completions/fasd.fish
+/home/aureooms/.config/fish/completions/fasd_cd.fish
+/home/aureooms/.config/fish/completions/s.fish
+/home/aureooms/.config/fish/completions/sd.fish
+/home/aureooms/.config/fish/completions/sf.fish
+/home/aureooms/.config/fish/completions/z.fish
+/home/aureooms/.config/fish/completions/zz.fish
/usr/share/fish/vendor_functions.d/fisher.fish (line 1): No matches for wildcard “$source/{functions,conf.d,completions}/*”. See `help expand`.
string replace $source $fisher_path $source/{functions,conf.d,completions}/*
                                    ^
in command substitution
	called on line 142 of file /usr/share/fish/vendor_functions.d/fisher.fish
in function 'fisher' with arguments 'update'
/usr/share/fish/vendor_functions.d/fisher.fish: Unknown error while evaluating command substitution
in function 'fisher' with arguments 'update'
installing oh-my-fish/plugin-sudope
+/home/aureooms/.config/fish/functions/__fasd_print_completions.fish
+/home/aureooms/.config/fish/functions/a.fish
+/home/aureooms/.config/fish/functions/d.fish
+/home/aureooms/.config/fish/functions/f.fish
+/home/aureooms/.config/fish/functions/fasd_cd.fish
+/home/aureooms/.config/fish/functions/init.fish
+/home/aureooms/.config/fish/functions/s.fish
+/home/aureooms/.config/fish/functions/sd.fish
+/home/aureooms/.config/fish/functions/sf.fish
+/home/aureooms/.config/fish/functions/z.fish
+/home/aureooms/.config/fish/functions/zz.fish
+/home/aureooms/.config/fish/completions/a.fish
+/home/aureooms/.config/fish/completions/d.fish
+/home/aureooms/.config/fish/completions/f.fish
+/home/aureooms/.config/fish/completions/fasd.fish
+/home/aureooms/.config/fish/completions/fasd_cd.fish
+/home/aureooms/.config/fish/completions/s.fish
+/home/aureooms/.config/fish/completions/sd.fish
+/home/aureooms/.config/fish/completions/sf.fish
+/home/aureooms/.config/fish/completions/z.fish
+/home/aureooms/.config/fish/completions/zz.fish
installing wfxr/forgit
+/home/aureooms/.config/fish/conf.d/forgit.plugin.fish
3 updated plugin/s
```

My workaround so far is to run the update again until it succeeds without hiccups:

```
fetching https://codeload.github.com/wfxr/forgit/tar.gz/HEAD
fetching https://codeload.github.com/oh-my-fish/plugin-sudope/tar.gz/HEAD
fetching https://codeload.github.com/oh-my-fish/plugin-fasd/tar.gz/HEAD
installing oh-my-fish/plugin-fasd
+/home/aureooms/.config/fish/functions/__fasd_print_completions.fish
+/home/aureooms/.config/fish/functions/a.fish
+/home/aureooms/.config/fish/functions/d.fish
+/home/aureooms/.config/fish/functions/f.fish
+/home/aureooms/.config/fish/functions/fasd_cd.fish
+/home/aureooms/.config/fish/functions/init.fish
+/home/aureooms/.config/fish/functions/s.fish
+/home/aureooms/.config/fish/functions/sd.fish
+/home/aureooms/.config/fish/functions/sf.fish
+/home/aureooms/.config/fish/functions/z.fish
+/home/aureooms/.config/fish/functions/zz.fish
+/home/aureooms/.config/fish/completions/a.fish
+/home/aureooms/.config/fish/completions/d.fish
+/home/aureooms/.config/fish/completions/f.fish
+/home/aureooms/.config/fish/completions/fasd.fish
+/home/aureooms/.config/fish/completions/fasd_cd.fish
+/home/aureooms/.config/fish/completions/s.fish
+/home/aureooms/.config/fish/completions/sd.fish
+/home/aureooms/.config/fish/completions/sf.fish
+/home/aureooms/.config/fish/completions/z.fish
+/home/aureooms/.config/fish/completions/zz.fish
installing oh-my-fish/plugin-sudope
+/home/aureooms/.config/fish/functions/init.fish
+/home/aureooms/.config/fish/functions/key_bindings.fish
+/home/aureooms/.config/fish/functions/sudope.fish
installing wfxr/forgit
+/home/aureooms/.config/fish/conf.d/forgit.plugin.fish
3 updated plugin/s
```

**Comment by jorgebucaran** [comment]
Hey, @aureooms. I think you're using an old version of Fisher. Upgrade using `fisher update jorgebucaran/fisher` or just `fisher update`.

Also, what plugins are you trying to install? I think there may be one or two that we don't support like `plugin-fasd` or `plugin-sudope`. Fortunately, there's a PR to add Fisher support to one of those here: https://github.com/oh-my-fish/plugin-sudope/pull/16.

**Comment by aureooms** [comment]
Hi @jorgebucaran. The output above is the one I get when I run `fisher update`. I am running Fisher version 4.1.0 (installed via [the `fisher` AUR package](https://aur.archlinux.org/packages/fisher).

The plugins I use are
```
oh-my-fish/plugin-sudope
oh-my-fish/plugin-fasd
wfxr/forgit
```

**Comment by jorgebucaran** [comment]
I know you're using and older Fisher because that output doesn't match the latest Fisher. 

Upgrade to the latest Fisher and the problem should go away. 

> **Note**: I only officially support the installation method described in the README. I don't know how the AUR package works.

**Comment by jorgebucaran** [comment]
About the plugins: 

- use @ngmoviedo's Sudope fork until the maintainer decides to merge his PR.
- oh-my-fish/plugin-fasd uses `init.fish` files, which we [no longer support]( https://github.com/jorgebucaran/fisher/issues/582).
  - The TL;DR is that Oh My Fish and their plugin ecosystem is essentially abandoned and they haven't caught up with modern Fish. I recommend you stop using Oh My Fish plugins. Create your own or create a plugin request [here](https://www.reddit.com/r/fishshell/).
- wfxr/forgit seems to be fine, but the author clearly doesn't use Fish, because their code is not idiomatic, e.g., they put everything inside one big configuration snippet, instead of using functions to leverage Fish autoloading.

**Comment by jorgebucaran** [comment]
@aureooms About the plugins: 

- use @ngmoviedo's Sudope fork until the maintainer decides to merge his PR.
- **oh-my-fish/plugin-fasd** uses an `init.fish` file. We [no longer support]( https://github.com/jorgebucaran/fisher/issues/582) `init.fish` files.
  - The TLDR is that Oh My Fish and their plugin ecosystem are essentially abandoned and they never caught up with modern Fish. I recommend not using Oh My Fish plugins. Consider making your own (it's not so hard) or create a plugin request [here](https://www.reddit.com/r/fishshell/) and someone will probably build it.
- **wfxr/forgit** seems alright 👍, but the author doesn't not idiomatic Fish, e.g., they put everything inside one big configuration snippet, instead of using functions to leverage Fish functions autoloading.

**Comment by jorgebucaran** [comment]
About the plugins: 

- Please use @ngmoviedo's Sudope fork until the maintainer decides to merge his PR.
- **oh-my-fish/plugin-fasd** uses an `init.fish` file. We [no longer support]( https://github.com/jorgebucaran/fisher/issues/582) `init.fish` files.
  - The TLDR is that Oh My Fish and their plugin ecosystem are essentially abandoned and they never caught up with modern Fish. I recommend not using Oh My Fish plugins. Consider making your own (it's not so hard) or create a plugin request [here](https://www.reddit.com/r/fishshell/) and someone will probably build it.
- **wfxr/forgit** seems alright 👍, but the author doesn't know idiomatic Fish, e.g., they put everything inside one big configuration snippet, instead of using functions to leverage Fish functions autoloading.

**Comment by jorgebucaran** [comment]
Hey, @Scrumplex. Maybe you could shed some light here as the maintainer of the AUR package?

**Comment by Scrumplex** [comment]
Hi there. The AUR package uses the latest Git tag (in this case 4.1.0). I am sure that updating fisher itself via `fisher install jorgebucaran/fisher` would use the latest git commit instead. That might be why @aureooms might be using an older version. 

In fact when using fisher-git from the AUR (which builds from the latest commit) the output matches the newest version. I would suggest that you just create a new release for fisher, so I can package that one in the AUR.

**Comment by jorgebucaran** [comment]
@Scrumplex Thanks for the clarification. I'll do that later today. 👍

**Comment by aureooms** [comment]
Thanks for the help @jorgebucaran and @Scrumplex. I will look into forking the plugins or contributing to them.

**Comment by jorgebucaran** [comment]
That's awesome @aureooms, let me know if you need help with anything. If you need me, you can [find me here](https://gitter.im/fish-shell/fish-shell).
