### ISSUE TITLE
Support comments in fish_plugins file

### ISSUE THREAD

**Issue by mattmc3** [jorgebucaran/fisher#635]
It would be very helpful to be able to comment out a plugin, but not remove it from the `fish_plugins` file. Are you open to skipping over lines that begin with a hash (#) as a comment?

**Comment by jorgebucaran** [comment]
@mattmc3 Could you elaborate on your use case a bit more?

**Comment by jorgebucaran** [comment]
Could you elaborate on your use case a bit more?

**Comment by mattmc3** [comment]
I can see a few different important use cases.

Some plugin names aren't really descriptive about what they are or what they do. For example, edc/bass is cleverly named, but not obvious what it's for, so it's nice to have something like this in fish_plugins:

```shell
# bass is used to make it easy to use utilities written for Bash in fish
edc/bass
```

Secondly, as a fish plugin developer, it's also handy to comment out my own published fish plugins when I'm making changes.

```shell
# Normally I want my fish-up plugin, but as I make changes to it it's nice to comment it out
# and use my dev version in a different place on my machine.
# mattmc3/fish-up
```

And finally, sometimes I try out a plugin, but then remove it but want to keep it around for reference.

```shell
# plugins I use
jorgebucaran/fisher
mattmc3/fish-up

# archived plugins
# edc/bass
```

This is not a novel concept, as many other plugin managers do this. For example, a few popular ZSH ones do this:
- [Antibody](https://getantibody.github.io/usage/)
- [ZGen](https://github.com/tarjoilija/zgen/blob/0b669d2d0dcf788b4c81a7a30b4fa41dfbf7d1a7/zgen.zsh#L398)

I can understand that fisher is a little different in that it modifies the fish_plugins file rather than having it all be hand edited, so doing things like `fisher remove` might leave comment artifacts, but that's totally fine. If you are hand editing your fish_plugins file to add comments, that's the price you pay. Hope this helps see the usefulness.

**Comment by jorgebucaran** [comment]
@mattmc3 Take it for a spin:

```fish
fisher remove jorgebucaran/fisher
fisher install jorgebucaran/fisher@comments
```

> For example, edc/bass is cleverly named, but not obvious what it's for...

Maybe [replay.fish](https://github.com/jorgebucaran/replay.fish) has the best of both worlds. 😉

**Comment by jorgebucaran** [comment]
I'm going to pass on this feature request. I need to be strict about what goes into Fisher to avoid feature creep, rather than try to please everyone in the community. I was close to go ahead with this until I realized that inline comment support increases the complexity of the implementation and I don't want to ship mediocre comment support either. 

FWIW, let me address each of the different use cases described so hopefully you can see this in a new light:

> For example, `edc/bass` is cleverly named, but not obvious what it's for, so it's nice to have something like this in fish_plugins:

Please be careful about what you install in your system. If you can't remember what a plugin is for anymore, maybe it's time to remove it. You're also looking in the wrong place for plugin descriptions. Use `functions --verbose --details`:

```console
$ functions --verbose --details fisher
/home/jb/.config/fish/functions/fisher.fish
autoloaded
3
scope-shadowing
Fish plugin manager
```

> Secondly, as a fish plugin developer, it's also handy to comment out my own published fish plugins when I'm making changes.

I also [work on a ton](https://github.com/jorgebucaran?tab=repositories&q=&type=public&language=shell) of Fish plugins, and I often find myself switching between local and remote installations. I also implemented comments in the `@comments` branch and have been using it for about 2 months. I was especially active during this period as I've been porting all my stuff to  Fish `3.0`. Comments neither improved nor worsened my experience. 

> And finally, sometimes I try out a plugin, but then remove it but want to keep it around for reference.

Frankly, I find it a lot easier and faster to type `fisher install` <kbd>Tab</kbd> and navigate the command history to locate whatever I've once installed. This was a fair point, though, but not compelling enough to justify adding this feature.

> `fisher remove` might leave comment artifacts, but that's totally fine. If you are hand editing your `fish_plugins` file to add comments, that's the price you pay.

I don't want to pay that price. 😉

**Comment by mattmc3** [comment]
While I disagree and am disappointed (it's not a lot of code to scrub lines that begin with #), I appreciate the thoughtful reply and the work that goes into maintaining any feature. I can maintain my own fork to meet this need if it's not a benefit to the rest of the user base.

**Comment by jorgebucaran** [comment]
Check out my latest push to `@comments`. I managed to simplify the implementation, but still no inline-comments. If you happen to work on it and find a more compact solution, ping me, please. I'm not sure for how long I'll keep the branch around, though.

**Comment by soraxas** [comment]
I too would prefer to have an ability to place comments in the new `fish_plugins` file. I think this used to be the case in `fishfile` and I had used this feature intensively (both standalone comments and the inline comments capability). 

1. I do not agree that
> inline comment support increases the complexity of the implementation

as the builtin fish `string` operation can handle stripping hash comment easily, and `#` is not a valid git repository name so treating hash as the comment starting character will unlikely to breaks the storing of repo name in `fish_plugins` (valid repo characters are letters, digits, '_', '-' and '.' only).

2. Secondly, storing comments in (the original) `fishfile` was very useful for version tracking these "dotfiles" across my multiple computers. There are often times where I need to comment away some plugins because certain plugins are tied with some commandline utilities and they aren't available or installed in my other computers. For example, I'm using fish in my main laptop, a remote server (with limited utilities) and WSL, where they might have different set of fisher plugins that I'm using on those. I think comments to describe the plugins and the ability to comment them out is a very realistic and functional appraoch.

> Frankly, I find it a lot easier and faster to type fisher install Tab and navigate the command history to locate whatever I've once installed

3. I think relying on command history is a very poor way to keeping track of things (command history can very easily disappear), and most importantly this also wouldn't work across computers.

**Comment by jorgebucaran** [comment]
Command history will not disappear unless you make it so, and I think using it is way faster and more efficient than opening and inspecting a file. I rarely open `fish_plugins`, but I agree that comments are useful. 

Maybe you can try Fisher from my `@comments` branch for a few days and see how it goes. Like everything, nothing is set in stone, and there's always the possibility to reconsider.
