### ISSUE TITLE
Quieter update

### ISSUE THREAD

**Issue by tuxiqae** [jorgebucaran/fisher#641]
Would it be possible to make `fisher update` less verbose?

Currently it prints info regarding each and every plugin it tries to update, and says it got updated even if nothing changed.
I think that it would be better for it to print by default only the plugins that were actually updated, and in the end conclude it all with a list of updated plugins.

For example, that's my current output:
![image](https://user-images.githubusercontent.com/39622904/103143251-fcbe8c00-471a-11eb-8640-565bc9ded085.png)
 

Thanks for this amazing plugin manager!

**Comment by jorgebucaran** [comment]
The challenge is to reliably detect if a plugin requires an update or not. It's usually so fast to download a plugin that we simply don't care. It would be quite impressive to skip over plugins that don't need to be updated, but we'd probably want to add a `--force` flag to update it anyway since updating has also the effect of erasing the plugin from the environment and re-enabling it, followed by an `update` event, which I find valuable during plugin construction.

If you just want a quieter `install`, `update`, and `remove`, we could look into adding a `--quiet` flag, or just pipe the output to `/dev/null`.

**Comment by tuxiqae** [comment]
@jorgebucaran, so why not actually add a `--quiet` flag which will only print `X plugins were successfully updated`?

To me that sounds the best out of all of those.

**Comment by jorgebucaran** [comment]
@tuxiqae Could work! I don't particularly need this, so feel free to send a PR and we can take it from there.

**Comment by tuxiqae** [comment]
Unfortunately I don't have much spare time these days, not sure when I'd be able to take care of it.
