### ISSUE TITLE
No longer compatible with omf

### ISSUE THREAD

**Issue by soraxas** [jorgebucaran/fisher#654]
Sorry about the push and force-push to the PR's branch. I did not meant to add extra commits to the PR but merely forgot to switch to a different feature branch when I created the PR (which causes new commits shows up in the PR automatically). I was just modifying my fork to fix some of the breakages from the new fisher version (and didn't notice those affected the PR), and I did not mean to create any annoyance. I apologise for that.

One thing that I want to point out is that previously I've been using `fisher` to install `omf` plugins but with the new depreciation they no longer works (a lot of omf plugins and themes uses `init.fish` and top-level functions). So I think with your new depreciation, you should update your `README.md` fle

> - ...
> - Oh My Fish! plugin support.

of stating `fisher` is no longer compatible with oh my fish plugins. But overall thanks for the great work. Cheers.

**Comment by jorgebucaran** [comment]
Fisher is compatible with a large number of Oh My Fish plugins since not all of them use `init.fish` or `uninstall.fish`, so stating "Oh My Fish! plugin support" is not far-fetched at all. "Support (with caveats)" might be more accurate, though. 

Maybe I'll add that later.

I have also spoken about Oh My Fish non-canonical baggage, see: https://github.com/laughedelic/pisces/pull/26#issuecomment-734070660, and the need to move on from it.
