### ISSUE TITLE
"fish_plugins" file not found: "update"

### ISSUE THREAD

**Issue by KerickHowlett** [jorgebucaran/fisher#738]
In my attempt to experiment and personalize some dotfiles that I forked, I came across an issue when the bootstrap script attempts to install/update the list of fisher plugins after creating a symlink for them.

I'm not sure why this is happening, because when I copy the file (or even when I create a symlink using `cp -s [plugin_filepath]` it works just fine; however, I don't know too much about what makes `cp -s` different from `ln -s`, and I'd rather not overcomplicate the `link_file` script function that's embedded in the script.

I'm not sure if fisher needs an update or if there's a better way to go about creating the symlink or if this is just a plain & simple bug, so I'm hoping someone could shed some light on it.

To recreate the bug, go to my forked repo [HERE](https://github.com/KerickHowlett/dotfiles.fish), and then enter the following commands (assuming you're already running fish and not bash or zsh):
```fish
cd ./script
fish bootstrap.fish
```
I'd also recommend taking advantage of the `devcontainer` I have set up, so you don't end up muddying up your own system—assuming you have Docker installed and are using Visual Studio Code.

**Comment by jorgebucaran** [comment]
Make sure that script installs or updates only when Fish is interactive `status is-interactive`.

**Comment by KerickHowlett** [comment]
It still doesn't work _outside_ the script.

Initially, when I thought it was just the script, I tried running the update command manually with the symlink still present, and I ran into the same error.

**Comment by Susensio** [comment]
Could be related to #741

**Comment by jorgebucaran** [comment]
Hey @KerickHowlett

Just had a chance to circle back to this and noticed that your [dotfiles.fish](https://github.com/KerickHowlett/dotfiles.fish) isn't active anymore. It's a bit tricky to figure out if it's a Fisher issue or not. It might be related to that bootstrap script you mentioned, but it could be on our end too. 

That error pops up when the `fish_plugins` is missing. It's possible that it happened because Fisher wasn't installed following the instructions we provided.

**Comment by KerickHowlett** [comment]
I think I may have deleted it at some point, because I scrapped it in favor of something else (that I've yet to start on). lol

It was forked from someone else's repo, however; I don't know if they ever had issues with it — probably not — but here's the [link](https://github.com/caarlos0/dotfiles.fish/blob/main/script/bootstrap.fish#L95-L96).

**Comment by jorgebucaran** [comment]
It seems that Carlos hasn't bumped into this either (https://github.com/caarlos0/dotfiles.fish/issues/23).

I'm gonna close this now because there's nothing actionable we can do at this point, and it's not even clear if it's a Fisher issue. https://github.com/jorgebucaran/fisher/issues/741 might actually fix it, but I'm not sure how I'll tackle that issue yet, so I don't wanna keep this open depending on it.

**Comment by KerickHowlett** [comment]
It's all good. Admittedly, I forgot I even posted this issue; it was so long ago. 😅
